### ISSUE TITLE
Remove INSTAGIB Barrel at Start of Level

### ISSUE THREAD

**Issue by rlonchar** [egingric/2015-Racing-Game#193]
This Barrel should be removed. The level does not even start and you can be INSTAGIBED

INSTAGIB - referring to one-hit kills in games where the victim is instantly turned into 'giblets', or explodes or dies.
![bug02](https://cloud.githubusercontent.com/assets/7013553/6964617/f7598330-d918-11e4-8554-c2221d50a6e2.jpg)

**Comment by jhunterRingling** [comment]
removed!
