### ISSUE TITLE
Car Rig is not handling well

### ISSUE THREAD

**Issue by tmundy** [egingric/2015-Racing-Game#202]
![halphaphlpalhaplhpalhpal](https://cloud.githubusercontent.com/assets/11721474/6965594/c71c0b68-d920-11e4-8e5b-36fdf1c0ad83.PNG)

These cylinders are too low, I think, and a lot of people are having trouble completing stunts using this car. Please try raising the cylinders a bit so that the collision works better

**Comment by ahargrov** [comment]
Rotated the sphylls to be straight and raised a bit. My car isn't the default anymore, but hopefully this still resolves the issue.
