### ISSUE TITLE
Car doesnt respwan

### ISSUE THREAD

**Issue by ealfonso1** [egingric/2015-Racing-Game#226]
Whenever the car is destroyed it does not respawn and the player is forced to restart the level

**Comment by tcallaha** [comment]
I believe this has been fixed, I have removed the custom car code from the level (April 2nd, 4:30 PM) and, should things go as planned, it will now spawn the vehicle you have chosen in the level select screen.

I will test and make sure later on in the evening.

**Comment by tcallaha** [comment]
Yep, it's been fixed!
