### ISSUE TITLE
Remove level BP code to spawn your vehicle.

### ISSUE THREAD

**Issue by egingric** [egingric/2015-Racing-Game#267]
Remove level BP code to spawn your vehicle.

**Comment by ltoomey** [comment]
When the level starts the car now spawns in a seemingly random location and not the start - if it is destroyed it does spawn at the intended player start... I heard other people are having the same issue - is there some fix?

**Comment by egingric** [comment]
I checked in a save game file. should fix the problem.

Regards,
-Eric
