### ISSUE TITLE
Kind of confusing after the slide

### ISSUE THREAD

**Issue by rgerson** [egingric/2015-Racing-Game#28]
attached is a photo of the area i'm referencing. when you fall off of the slide there is no indication of where to go, so i went straight.... into a wall. 
![dmolonywheredoigo](https://cloud.githubusercontent.com/assets/11725832/6906194/383f1362-d6fb-11e4-84e0-4afee01d9168.PNG)

**Comment by dmolony26** [comment]
Landscape reworked to add direction.
