### ISSUE TITLE
Green Shadow?

### ISSUE THREAD

**Issue by jhunterRingling** [egingric/2015-Racing-Game#302]
Shadows off the car turn green and appear unrealistic.
![bug01](https://cloud.githubusercontent.com/assets/11721406/7005362/4e1593b0-dc45-11e4-9ae8-c08e0da4efeb.jpg)

**Comment by sschneid1** [comment]
This issue has been submitted before. It has to do with the lighting being off-reference. It will be fixed after I fix A-priority issues.
