### ISSUE TITLE
Blocking Collision 

### ISSUE THREAD

**Issue by gLandivar** [egingric/2015-Racing-Game#315]
![hunter2](https://cloud.githubusercontent.com/assets/11721386/7005733/d15aabae-dc48-11e4-9fc0-fac2ab5d0fbc.JPG)
![hunter](https://cloud.githubusercontent.com/assets/11721386/7005734/d15d152e-dc48-11e4-945e-9ba5ebf54633.JPG)

Invisible collision

**Comment by jhunterRingling** [comment]
Fixed!
