### ISSUE TITLE
Green Jump Arrow Collision

### ISSUE THREAD

**Issue by tmundy** [egingric/2015-Racing-Game#316]
The collision on the glowing green arrow of the jumps makes it very difficult to successfully complete the jump. This needs to either be reworked or removed

![collisionagagiangian](https://cloud.githubusercontent.com/assets/11721474/7005785/5c599288-dc49-11e4-919b-57d6c2609bdd.PNG)

**Comment by jhunterRingling** [comment]
Fixed it! The collision on the arrow was on, so it should work now.
