### ISSUE TITLE
Add some specular highlights to your glass tube material

### ISSUE THREAD

**Issue by scarrollrcad** [egingric/2015-Racing-Game#337]
![screenshot00001](https://cloud.githubusercontent.com/assets/6991620/7051237/d7459fda-ddf4-11e4-8e5a-c5894263a16a.png)

**Comment by mfrorer** [comment]
Fixed it! I added more specularity with a blue emissive and a panning water normal map. The top and bottom of the tubes now look like some sort of sci-fi plasma surface.
