### ISSUE TITLE
 Best of Ringling BLOCKER: Fix your bricks

### ISSUE THREAD

**Issue by scarrollrcad** [egingric/2015-Racing-Game#340]
Apply Ryland and my feedback from critique:

Form is bad (make them rectangular)
Noise level on texture to large (reduce scale)
Lighting is broken?  Where's the grout?

**Comment by PsteinRCAD** [comment]
On it.

**Comment by PsteinRCAD** [comment]
They are re-done. I do not think they fit as well with the style as the older ones, but everything asked of here has been changed. I'm re-building lighting now, and will resubmit as soon as it's finished.
