### ISSUE TITLE
Level loads

### ISSUE THREAD

**Issue by egingric** [egingric/2015-Racing-Game#345]
Make sure your kids test their level loads!

**Comment by rlonchar** [comment]
You had most of them right. The ones that were wrong are fixed.

**Comment by egingric** [comment]
@rlonchar General method for fixing bugs: If you think you fixed an issue, don't close the bug. Mark it fixed then assign it to the person who assigned it to you. That person is responsible for verifying the fix and closing the bug.

**Comment by rlonchar** [comment]
I thought I just hit comment on this like I did for the Light issue. My
bad, must have hit Comment and Close.

_Ryland Loncharich_
Ringling College of Art + Design
Computer Animation\* |\* Game Art and Design Faculty

**Comment by egingric** [comment]
Roger that.
