### ISSUE TITLE
My level in the player select is wrong

### ISSUE THREAD

**Issue by datamez** [egingric/2015-Racing-Game#350]
My level in the player select is wrong. It is of my old graybox that was deleted

**Comment by egingric** [comment]
Roger that. What is the name and location of the level that you would like to load?

**Comment by datamez** [comment]
Dtamez_NeoTokyoShowdown.umap and it's in ga228>02>Dtamez in that folder.

On Wed, Apr 22, 2015 at 10:44 AM, Eric D. Gingrich <notifications@github.com
