### ISSUE TITLE
lawnmower ramp

### ISSUE THREAD

**Issue by ltoomey** [egingric/2015-Racing-Game#36]
If you don't have enough speed going up the lawnmower  you cannot make it up the ramp. The player is forced to press delete and reset or manually drive over into a kill volume for a 2nd try.
![bug](https://cloud.githubusercontent.com/assets/11725823/6906386/93d0e272-d6fc-11e4-8bfd-8d7f57eb2263.png)

**Comment by dmolony26** [comment]
Ramp lowered.
