### ISSUE TITLE
Vehicle spawns in middle of nowhere in both PIE and Standalone.

### ISSUE THREAD

**Issue by zaqschlanger** [egingric/2015-Racing-Game#362]
Car will spawn in space, which appears to not be world 0 because that is an actual part of my geo, so it looks like you spawn under your level. Also, sometimes you are unable to move until you restart the game in standalone.

**Comment by egingric** [comment]
I think I may have fixed the spawn location issue. Please get latest VH_GameMode and test your map.

**Comment by egingric** [comment]
@mhadley1 @dmolony26 @lglanvil

**Comment by egingric** [comment]
Assuming this is fixed.
