### ISSUE TITLE
Fix Your Error

### ISSUE THREAD

**Issue by egingric** [egingric/2015-Racing-Game#366]
Please fix this error ASAP.
![dtamezerror](https://cloud.githubusercontent.com/assets/3945065/7234058/87d01d6a-e752-11e4-89a7-6851379dc583.PNG)

**Comment by egingric** [comment]
Fix this now brutha. Not later.

**Comment by datamez** [comment]
​I'm not seeing the error. This is the only one I see but I'm not sure what
it is or how to fix it. My level is still not loading from the level select
screen. Maybe your seeing something I'm not. I'm not sure but I'm gonna be
in the labs most of tomorrow afternoon and night so if you get back to be
I'll be sure to fix it as soon as possible.

Thanks,
Danny T.

**Comment by egingric** [comment]
I see you have the file checked out. You have probably not checked in the
version with the error fixed??

Regards,
-Eric

**Comment by egingric** [comment]
Did you give me a bug on your level not loading from level select?

Regards,
-Eric

**Comment by datamez** [comment]
I'll double check when I get to the labs later this afternoon but I will
admit I am a bit confused and also here is the link to github bug report.
https://github.com/egingric/2015-Racing-Game/issues/350
