### ISSUE TITLE
Fix your character and anims ASAP!

### ISSUE THREAD

**Issue by egingric** [egingric/2015-Racing-Game#375]
Hi, I am trying to put your characters and anims in the vehicle select screen. You need to fix your issues ASAP! See below for your name and issues.

0 @ahargrov   no anims
3 @Cfarinas  = Made new skeletons for each anim. This is wrong and these anims should be re-imported with the correct skeleton. They should then start working. You have duplicate copies of the anims in your directory which should be deleted.
4 @cwhitmor  no anims
7 @datamez no anims & no character!
11 @grosnack  = anims on trents skeleton instead of yours. Re-import existing anims using your mesh and they should start working.
13 @jClark3   = No anims.
17 @kkavanau  = no character, no anims!
19 @lglanvil  = no character, no anims!
24 @mrice1  = no character, no anims!
28 @rgerson  = no character, no anims!

**Comment by egingric** [comment]
25 @nmarten  = no anims.
26 @pcsaengc  = no anims
29 @smundo1  = no skeleton for anims.
36 @turbon  = no anims.
@rlonchar = Tell your kids to get this done today!

**Comment by egingric** [comment]
14 @deraj8  = duplicate anims in your directory. Delete!
15 @jlewinringling  = no skeleton on anims
37 @ykim1  = duplicate anims in your directory. delete.

**Comment by jhunterRingling** [comment]
Deleted extra Anims.
Also why does only one of the characters appear off the screen? Most seem to spawn on the screen and end up walking off. Is this still being worked on?

**Comment by egingric** [comment]
They spawn on screen because you are supposed to animate them to the root rather than away from it. Trent is the only one that is correct currently. Jamie says he will get you to fix it in class tomorrow, but please feel free to fix it now. :-)

**Comment by jhunterRingling** [comment]
okay

**Comment by egingric** [comment]
@Cfarinas I see you updated the duplicate copies of the anims in your directory which should be deleted. I however am not using these duplicates which should be deleted, so you should instead update the ones that you made in the correct directory VehicleGame\Content\Maps\vehicleSelect\EntranceAnims\
