### ISSUE TITLE
Character animation not running on rgerson_entrance/idle

### ISSUE THREAD

**Issue by rgerson** [egingric/2015-Racing-Game#381]
Fixed mirrored rotation (facing the wrong way) with new parent root joint (via jamie's instruction) and imported new skeletal mesh, entrance animation, and idle (all to have the new root joint).

Followed same naming convention, but when car loads into scene, character displays no animation.

**Comment by egingric** [comment]
I replaced your deleted sk with new character. You are not supposed to delete the character Randy. Stop doing that.
